//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr6Auth.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft
    {
        public Aircraft()
        {
            this.Flights = new HashSet<Flights>();
        }
    
        public int Id { get; set; }
        public string Model { get; set; }
        public int Capacity { get; set; }
        public string RegistrationNumber { get; set; }
    
        public virtual ICollection<Flights> Flights { get; set; }
    }
}
