//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr6Auth.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pr5DBEntities1 : DbContext
    {
        public pr5DBEntities1()
            : base("name=pr5DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Users> Users { get; set; }
        public DbSet<Aircraft> Aircraft { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<Flights> Flights { get; set; }
        public DbSet<Tickets> Tickets { get; set; }
    }
}
