//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr6Auth.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int FlightId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal FinalPrice { get; set; }
        public string Class { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Flights Flights { get; set; }
    }
}
